name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: wtc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .
      - run: nix flake check
